### ISSUE TITLE
收费的API是怎么实现的

### ISSUE THREAD

**Issue by AbleCats** [Alex-xd/seeMusic#3]
如题  0 0

**Comment by Alex-xd** [comment]
[歌曲接口](http://music.163.com/api/song/detail?ids=[29567189]) 里有低品的url，但是其余品质的要根据对应xMusic字段下的dfsId解密出来

"http://m2.music.126.net/gQDmHxjY_gAtRE-RKqDQJw==/1413971968361530.mp3"
最后面的是dfsId 中间插的是对应品质的dfsId。

解密我在后台做的，就是先转成字节码再md5一下

**Comment by AbleCats** [comment]
我是问的是付费歌曲的API是怎么做的呢 0 0 如果不方便回答就算了...

**Comment by Alex-xd** [comment]
API在代码里的位置在[https://github.com/Alex-xd/seeMusic/blob/dev/src/api/API.js#L22](https://github.com/Alex-xd/seeMusic/blob/dev/src/api/API.js#L22) 和 [https://github.com/Alex-xd/seeMusic/blob/dev/src/api/address.js#L9](https://github.com/Alex-xd/seeMusic/blob/dev/src/api/address.js#L9)，这个地址是我后台JAVA提供的，原理就是转个字节码再md5一下不难吧。

原始API是网易的，就像这个[http://music.163.com/api/song/detail?ids=[29567189]](http://music.163.com/api/song/detail?ids=[29567189])，但是只能拿到低品质的url，高品质的没有，在后台解密可得。

@AbleCats
